### ISSUE TITLE
Can't get knap to use pdfs.

### ISSUE THREAD

**Issue by AndOrangutan** [frabjous/knap#10]
Using the setup given in README without changing anything works.

![image](https://user-images.githubusercontent.com/40435989/187098528-85eeec7f-c620-4c81-96e9-c3959733a94a.png)

Changing `mdoutputext = "html"` to "pdf", such as below, doesn't work.
```lua
local wk = require("which-key")

local gknapsettings = {
    mdoutputext = "pdf",
    mdtohtml = "pandoc --standalone %docroot% -o %outputfile%",
    mdtohtmlviewerlaunch = "falkon %outputfile%",
    mdtohtmlviewerrefresh = "none",

    mdtopdf = "pandoc %docroot% -o %outputfile%",
    mdtopdfviewerlaunch = "sioyek %outputfile%",
    mdtopdfviewerrefresh = "none",

    delay = 250,
}

vim.g.knap_settings = gknapsettings

wk.register({
    ["<F5>"] = { function() require("knap").process_once() end, "Knap Process Once"},
    ["<F6>"] = { function() require("knap").close_viewer() end, "Knap Close Viewer"},
    ["<F7>"] = { function() require("knap").toggle_autopreviewing() end, "Knap Toggle Autoprevewing"},
    ["<F8>"] = { function() require("knap").forward_jump() end, "Knap Forward Jump"},
}, { mode =  "n" })
```
Knap says it starts a routine, but no previewer is started.
![image](https://user-images.githubusercontent.com/40435989/187098697-650f2cfd-1f81-40f9-a6bb-468204d461c6.png)

I originally thought it was because sioyek wasn't installed correctly, but after resolving that, I still have this issue.
![image](https://user-images.githubusercontent.com/40435989/187098749-839d4135-b146-437f-b7b1-95adce83087a.png)

**Comment by frabjous** [comment]
Your settings work fine for me. (Well, except I'm not using which-key, which I don't have installed. I doubt that's the issue, but you could try it without it.)

You should only see "knap routine started" for a short time. It should then say "process successful; refreshing preview" once the pandoc command is done running (or else show an error message if pandoc failed). Only then will it try to launch the viewer. Does `ps aux | grep pandoc` show the pandoc command still running? 

Have you tried with a more minimal document? Have you tried the pandoc command from the command line to make sure it finishes (in a reasonable amount of time)?

**Comment by AndOrangutan** [comment]
Ah ok, so it was the file. Got it to work on a more simple file. Still learning Pandoc, but that makes sense, it was a substantial file. Thank you so much.
