### ISSUE TITLE
Viewer autoloaded successfully only once on stock config

### ISSUE THREAD

**Issue by DMNinja** [frabjous/knap#16]
Not sure if it's user error so i'll refrain from assigning a label to avoid clutter.

The above behavior was independent of previewer (zathura/sioyek). On consequent uses, the previewer doesn't autosload but if opened and navigated to the file manually, it works. It seems that pandoc is executing normally. Pic related. It also seems knap.close_viewer doesn't work.
 
For debugging purposes i used the following stock config (found the readme). It is supplied below. The file is located under ~/.config/nvim/after/plugin/knap.lua (and thus is lazyloaded)

![image](https://user-images.githubusercontent.com/79472297/209363922-7c613258-12d5-49f4-b314-5242bd226b80.png)

```
-- set shorter name for keymap function
local kmap = vim.keymap.set

-- F5 processes the document once, and refreshes the view
kmap('i','<F5>', function() require("knap").process_once() end)
kmap('v','<F5>', function() require("knap").process_once() end)
kmap('n','<F5>', function() require("knap").process_once() end)

-- F6 closes the viewer application, and allows settings to be reset
kmap('i','<F6>', function() require("knap").close_viewer() end)
kmap('v','<F6>', function() require("knap").close_viewer() end)
kmap('n','<F6>', function() require("knap").close_viewer() end)

-- F7 toggles the auto-processing on and off
kmap('i','<F7>', function() require("knap").toggle_autopreviewing() end)
kmap('v','<F7>', function() require("knap").toggle_autopreviewing() end)
kmap('n','<F7>', function() require("knap").toggle_autopreviewing() end)

-- F8 invokes a SyncTeX forward search, or similar, where appropriate
kmap('i','<F8>', function() require("knap").forward_jump() end)
kmap('v','<F8>', function() require("knap").forward_jump() end)
kmap('n','<F8>', function() require("knap").forward_jump() end)

local gknapsettings = {
    htmloutputext = "html",
    htmltohtml = "none",
    htmltohtmlviewerlaunch = "falkon %outputfile%",
    htmltohtmlviewerrefresh = "none",
    mdoutputext = "html",
    mdtohtml = "pandoc --standalone %docroot% -o %outputfile%",
    mdtohtmlviewerlaunch = "falkon %outputfile%",
    mdtohtmlviewerrefresh = "none",
    mdtopdf = "pandoc %docroot% -o %outputfile%",
    mdtopdfviewerlaunch = "sioyek %outputfile%",
    mdtopdfviewerrefresh = "none",
    markdownoutputext = "html",
    markdowntohtml = "pandoc --standalone %docroot% -o %outputfile%",
    markdowntohtmlviewerlaunch = "falkon %outputfile%",
    markdowntohtmlviewerrefresh = "none",
    markdowntopdf = "pandoc %docroot% -o %outputfile%",
    markdowntopdfviewerlaunch = "sioyek %outputfile%",
    markdowntopdfviewerrefresh = "none",
    texoutputext = "pdf",
    textopdf = "pdflatex -interaction=batchmode -halt-on-error -synctex=1 %docroot%",
    textopdfviewerlaunch = "sioyek --inverse-search 'nvim --headless -es --cmd \"lua require('\"'\"'knaphelper'\"'\"').relayjump('\"'\"'%servername%'\"'\"','\"'\"'%1'\"'\"',%2,%3)\"' --reuse-instance %outputfile%",
    textopdfviewerrefresh = "none",
    textopdfforwardjump = "sioyek --inverse-search 'nvim --headless -es --cmd \"lua require('\"'\"'knaphelper'\"'\"').relayjump('\"'\"'%servername%'\"'\"','\"'\"'%1'\"'\"',%2,%3)\"' --reuse-instance --forward-search-file %srcfile% --forward-search-line %line% %outputfile%",
    textopdfshorterror = "A=%outputfile% ; LOGFILE=\"${A%.pdf}.log\" ; rubber-info \"$LOGFILE\" 2>&1 | head -n 1",
    delay = 250
}

vim.g.knap_settings = gknapsettings
```

**Comment by frabjous** [comment]
You don't need to set the settings at all if you want to use the defaults. Try it without setting them at all. (Keep the keybindings but remove everything from `local gknapsettings = ` on.)

I recently changed the defaults due to changes to Sioyek 2.0, but forgot to update the README. I'll do that right away. 

What you have listed there are the defaults from the README, which are out of date. That might be the source of your problem; not sure. What version of Sioyek are you using?

If you still can't get it working: let me know: what keys are you pressing? What is actually happening when you do?

There are couple other things in your post that confuse me. What am I supposed to learn from the screenshot? That's a TeX file -- what does pandoc have to do with anything?

**Comment by DMNinja** [comment]
Thank you for the prompt response and sorry for the lack of definition in my OP. I'll try my best to convey my findings. I'll try to be verbose for purposes of archiving and future lookup. All comments are made for the commit `62eae7803d9d87d33513b3b565c6f5791f1de1ea`

> You don't need to set the settings at all if you want to use the defaults. Try it without setting them at all. (Keep the keybindings but remove everything from `local gknapsettings = ` on.)

Initially, i had switched to a zathura config, and reverted to the defaults for debugging purposes, since the latter were stable. KNAP works as intended with sioyek with just the keybindings, but zathura currently doesn't

> I recently changed the defaults due to changes to Sioyek 2.0, but forgot to update the README. I'll do that right away.

I wasn't aware of that, and i guess my issue resided there. Thanks for updating the README! 

> What you have listed there are the defaults from the README, which are out of date. That might be the source of your problem; not sure. What version of Sioyek are you using?

It appears to be the case. My version of Sioyek is 2.0.0.1

> If you still can't get it working: let me know: what keys are you pressing? What is actually happening when you do?

For sioyek specifically:
- `knap.process_once` processes the file and doesn't track your current carriage position when processed
- `knap.close_viewer` closes the viewer
- `knap.toggle_autopreviewing` refreshes the preview and doesn't track your current carriage position
- `knap.forward_jump` performs a one-time forward search, highlights and also moves the mouse cursor to the middle of the previewer window. The movement of the cursor is highly inconvenient, but that's a personal observation

Zathura doesn't open at all

> There are couple other things in your post that confuse me. What am I supposed to learn from the screenshot? That's a TeX file -- what does pandoc have to do with anything?

I'm sorry for the lack of clarity in my post. I'm not really used to submitting issues. I was trying to troubleshoot using [this post](https://github.com/frabjous/knap/issues/10#issuecomment-1229581997) where it's said that if pandoc failed, it'd throw an error. I just wanted to point out it wasn't a pandoc issue related to the config. The picture was there to showcase the "process successful" message, but no preview window. Hope this clarifies the above.

> Is the viewer not loading at all, or is it loading but not refreshing? What do you mean by "consequent uses"? Do you mean live changes to the same document loaded in the same instance of vim, or do you mean if you stop it and restart it, or do you mean if you quit vim and restart, or what?

The viewer was not loading at all. By "consequent uses" i meant that on the first use of each keybind, they worked as described above. Further use of keybinds didn't bring up / close the viewer in any vim use case (close,restart,quit), or the system itself (reboot,poweroff) or reinstalling everything (KNAP,sioyek,zathura) or deleting and re-making the associated files in their entirety.

It threw me off and was wondering why it worked only on the very first use of each keybind.

> The close_viewer function definitely won't work if you opened it manually.

Noted. No comments here

---

I'm willing to do further testing if you want troubleshooting data, but as it stands right now, the issue is resolved for sioyek. Still not sure why the zathura config doesn't work. Feel free to close the issue if you don't want any further info. Thanks again for the prompt response!

**Comment by frabjous** [comment]
I'm glad Sioyek is working now.

Can you post the exact config you were using for Zathura? I just tested the suggested config in the README for Zathura and I didn't have any issues.

Pandoc is used in the default config for markdown files, but it is not used for LaTeX files. The issue you linked to involved a markdown file. In your case the "process successful" means that pdflatex didn't encounter an error. Pandoc is not involved in any way.

**Comment by DMNinja** [comment]
> Can you post the exact config you were using for Zathura? I just tested the suggested config in the README for Zathura and I didn't have any issues.

Other than the keybinds, i used the following config on knap.lua, tested on a .tex file:

`vim.g.knap_settings = {
    textopdfviewerlaunch = "zathura --synctex-editor-command 'nvim --headless -es --cmd \"lua require('\"'\"'knaphelper'\"'\"').relayjump('\"'\"'%servername%'\"'\"','\"'\"'%{input}'\"'\"',%{line},0)\"' %outputfile%",
    textopdfviewerrefresh = "none",
    textopdfforwardjump = "zathura --synctex-forward=%line%:%column%:%srcfile% %outputfile%"
}`

Here's my zaturarc for reference:

`set sandbox none
set statusbar-h-padding 0
set statusbar-v-padding 0
set page-padding 1
set selection-clipboard wl-clipboard
map u scroll half-up
map d scroll half-down
map D toggle_page_mode
map r reload
map R rotate
map K zoom in
map J zoom out
map i recolor
map p print
map g goto top
map G goto bottom`

> Pandoc is used in the default config for markdown files, but it is not used for LaTeX files. The issue you linked to involved a markdown file. In your case the "process successful" means that pdflatex didn't encounter an error. Pandoc is not involved in any way.

Thanks for the clarification!

**Comment by frabjous** [comment]
Zathura (0.5.1) works for me with those settings. 

What do you get in the command line you type in the following in a terminal while you have the file open in neovim?

```
zathura --synctex-editor-command 'nvim --headless -es --cmd "lua require('"'"'knaphelper'"'"').relayjump('"'"'%servername%'"'"','"'"'%{input}'"'"',%{line},0)"' %outputfile%
```
Where you replace `%servername%` with the output of `:echo v:servername` from neovim's command line, and %outputfile% with the name of the output file (`something.pdf`, etc.) Leave `%{line}` and `%{input}` as is.

(Note: for multiline code, use three backticks the lines before and after, not just one, to get a full codeblock, not inline code.)

**Comment by DMNinja** [comment]
> Zathura (0.5.1) works for me with those settings.

Just for reference, I'm using zathura 0.5.1-1

> What do you get in the command line you type in the following in a terminal while you have the file open in neovim?
> 
> ```
> snip
> ```
> 
Servername is ```/run/user/1000/nvim.3100.0```

I think the return is indicative enough

```error: Built without synctex support, but synctex specific option was specified.```

Zathura was downloaded through pacman. It appears it doesn't build with synctex support by default.
 
> (Note: for multiline code, use three backticks the lines before and after, not just one, to get a full codeblock, not inline code.)

Thanks for the markdown tip :)

I guess this resolves the issue in question?

**Comment by frabjous** [comment]
You didn't mention what distro you're using, but you said it was installed through pacman. I'm using the version of zathura installed from the vanilla Arch repos myself, and it definitely supports synctex! 

Yes, version 0.5.1-1 (0.5.1 is the Zathura version, the -1 at the end is the PKGBUILD version number.)

Are you using `zathura-pdf-mupdf` or `zathura-pdf-poppler`? (For me it works with either one, but I'm just curious.) Does Zathura work just for viewing PDFs normally?

**Comment by DMNinja** [comment]
Sorry for the late response, but i've got good news!

> You didn't mention what distro you're using, but you said it was installed through pacman. I'm using the version of zathura installed from the vanilla Arch repos myself, and it definitely supports synctex!
> 

Upon this prompt, i checked the installed package. I'm running Artix-OpenRC and they have their own buildbot for packages. Something went wrong with the libsyntex opdep on their end. They fixed the bug, and i tested Zathura today. It now works as intended.

Thank you for the help in troubleshooting the issue. I hope it wasn't too much of a bother.

**Comment by DMNinja** [comment]
> You didn't mention what distro you're using, but you said it was installed through pacman. I'm using the version of zathura installed from the vanilla Arch repos myself, and it definitely supports synctex!
> 

Thanks to your suggestion, i looked up the package i am using. There was an issue with the package on my distribution (Artix-OpenRC), which is now resolved, and KNAP now works as intended.

I hope it wasn't too much of a bother for you.

**Comment by frabjous** [comment]
Not a problem. I'm glad it led to fixing an Artix bug! I had been using Artix on one of my systems till recently, but I don't think I used Zathura on it.
