### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by medwatt** [frabjous/knap#2]
How is this different from converting LaTex to pdf directly and seeing actually how the pdf looks? This is not meant as a criticism; just that I'm trying to assess whether this plugin can be useful to me.

**Comment by frabjous** [comment]
I'm not sure I understand the question. It *is* converting LaTeX to PDF and seeing how the PDF looks. The point of the plugin is that this happens automatically in the background while you type, and you don't need to do anything manually.
