### ISSUE TITLE
Error thrown by single-processing and auto-processing operations: attempt to index field 'v' (a null value).

### ISSUE THREAD

**Issue by RobinTruax** [frabjous/knap#21]
Hi Kevin, 

I'm attempting to recreate the default configuration for TeX and running into some issues. I've installed the plugin using vim-plug, which went successfully, and have Sioyek (managed with AppImageLauncher), TeXlive, and rubber all installed on the machine. I'm trying to get it to work for the most simple LaTeX file possible: 

```
\documentclass{article}
\begin{document}
Test
\end{document}
```

Unfortunately, it's throwing the following error. 

`E5105: Error while calling lua chunk: ...e/roshan/.config/nvim/autoload/plugged/knap/lua/knap.lua:28: attempt to ind
ex field 'v' (a nil value)`

The code it's referring to seems fairly innocuous: 

`local knap_max_col_width = (vim.v.echospace - 1)`

Have you run into this before, or do you know what it's a result of? I'm running neovim 0.4.4 and the newest versions of Sioyek, TeXlive, and rubber.

**Comment by frabjous** [comment]
The plugin requires neovim 0.7 or above, as it says in the first line of the readme.
