### ISSUE TITLE
Cannot open sioyek

### ISSUE THREAD

**Issue by Fireond** [frabjous/knap#22]
Environment: Mac OS Ventura 13.2.1
Use lazy.vim to install plugin, use default config.
I just map the key and press, it returns `process successful; launching preview` but with nothing happend. I have installed sioyek and restart my computer also, but still not work. Can you give me some advise or methods to debug? Thanks!

**Comment by frabjous** [comment]
I've never tested it on a mac, as the README makes clear. I cannot troubleshoot it on a mac, because I do not own one, and cross my fingers, never will. You've locked yourself in a walled garden, and therefore, have to be your own support on this one.

**Comment by Fireond** [comment]
Ok, thanks.
