### ISSUE TITLE
falkon opens a new tab on every save

### ISSUE THREAD

**Issue by anuvyklack** [frabjous/knap#3]
With default settings during markdown preview in falkon, instead of reloading the existing tab, the new tab page on every save opens.

**Comment by frabjous** [comment]
I cannot reproduce that problem.

What version of Falkon are you using?

Sounds like a problem with it, as this would be really weird way for it to behave. The plugin with default settings does *nothing* with Falkon when the document is saved; Falkon does the reloading by itself, and for me, it stays in the same tab. I assume it does this even if you edit a local html file viewed in Falkon without my plugin?

**Comment by anuvyklack** [comment]
Doesn't help

**Comment by anuvyklack** [comment]
On the last commit, everything is now working as it should!

**Comment by anuvyklack** [comment]
On e192b609ea78163d16984b638e8942665b5fa23e, I get the next:
Open neovim, press `F7`
`:echo b:knap_viewerpid`: 10726
```
$ ps -p 10726; echo $?
    PID TTY          TIME CMD
  10726 pts/2    00:00:01 falkon
0

$ pgrep falkon
10726
```

After I edit file the tab is updated and the output is the next

```
$ ps -p 10726; echo $?
    PID TTY          TIME CMD
  10726 pts/2    00:00:01 falkon
0

$ pgrep falkon
10726
```

**Comment by anuvyklack** [comment]
On 343959ecf532e7d7bba5debc3c4433d63be7fe5e the previous non-working commit
`:echo b:knap_viewerpid` : 14071

```
$ ps -p 14071; echo $?
    PID TTY          TIME CMD
1

$ pgrep falkon
13668
```

After file editing

`:echo b:knap_viewerpid` : 14939

```
$ ps -p 14939; echo $?
    PID TTY          TIME CMD
1

$ pgrep falkon
13668
```

**Comment by frabjous** [comment]
If that was the difference, it's mysterious why you still got it when you started it with all falkon instances closed, but so long as the new commit works, I'll mark this as solved.
