### ISSUE TITLE
Launching Preview on OSX Sonoma

### ISSUE THREAD

**Issue by Crenshinibon** [frabjous/knap#33]
With NeoVim (v0.10.0), Lazy and the latest knap version I get the following error when trying to lunch the preview:

```
E5108: Error executing lua: /Users/porsched/.local/share/nvim/lazy/knap/lua/knap.lua:134: attempt to call upvalue 'err_msg' (a nil value)
stack traceback:
        /Users/porsched/.local/share/nvim/lazy/knap/lua/knap.lua:134: in function 'get_os'
        /Users/porsched/.local/share/nvim/lazy/knap/lua/knap.lua:137: in main chunk
        [C]: in function 'require'
        /Users/porsched/.config/nvim/init.lua:157: in function </Users/porsched/.config/nvim/init.lua:156>

```

It seems as if this function is the problem:

```
function get_os()
    local os_current = vim.loop.os_uname().sysname
    local isWindows,j = string.find(os_current,"Windows")

    if os_current == "Linux" then
        return "linux"
    elseif isWindows ~= nil then
        return "windows"
    else
        err_msg("Unknown operating system")
    end
end
```

When I change it like this:

```
function get_os()
    local os_current = vim.loop.os_uname().sysname
    local isWindows,j = string.find(os_current,"Windows")

    if os_current == "Linux" then
        return "linux"
    elseif isWindows ~= nil then
        return "windows"
    else
        return "linux"
        --err_msg("Unknown operating system")
    end
end
```

I don't get the error and the preview is opening up as expected.

**Comment by andregpss** [comment]
I found that when using macOS, `vim.loop.os_uname().sysname` returns `Darwin` value. Can you confirm?
So, the following code must work in your machine:

```
function get_os()

    local os_current = vim.loop.os_uname().sysname
    local isWindows,j = string.find(os_current,"Windows")

    if os_current == "Linux" or os_current == "Darwin" then
        return "linux"
    elseif isWindows ~= nil then
        return "windows"
    else
        err_msg("Unknown operating system")
    end
end
```

**Comment by Crenshinibon** [comment]
Yes, this does work.

**Comment by Crenshinibon** [comment]
I'm not sure about the context of this function. But from the distance it's main purpose is to decide if it's Windows and then do something special. 

Maybe the following should be enough, then? What else is there other then "linux" (including MacOS) and "windows" where anyone would run neovim on.

```
function get_os()

    local os_current = vim.loop.os_uname().sysname
    local isWindows,j = string.find(os_current,"Windows")

    if isWindows ~= nil then
        return "windows"
    end
    return "linux" 

end
```

**Comment by Crenshinibon** [comment]
So actually it's not the question of the current os (when windows is the exception here and the rest behaves the same), but rather if it's windows or not. So maybe the os_cur thing should be is_windows ... just an idea. I have easy access to osx and linux but not so easy to windows (only on my sons gaming machine) ... but if I find the time, I might look into it.

**Comment by andregpss** [comment]
I also do not have access to macOS.
I prefer the @frabjous idea of identifying the OS system in use. It can be useful in the future.

**Comment by frabjous** [comment]
Not me. Since I don't have access to a mac, someone who does would need to make the changes and do a PR.

**Comment by frabjous** [comment]
Your code block is garbled in your post, so I can't even tell what I'm looking at. If you don't feel comfortable making the other changes suggested, you might just follow Crenshibon's original suggestion.

**Comment by frabjous** [comment]
I'm not at familiar with Lazy, and I don't know whether or not it can be used that way, but the error you're getting still says "attempt to call upvalue 'err_msg'", then I'd try modifying the actual knap.lua file. If you still get that error, then change the `err_msg` line to just say `return "linux"`.

**Comment by andregpss** [comment]
You can use the following command in NeoVim to print your OS name:

> `:lua print(vim.loop.os_uname().sysname)`
