### ISSUE TITLE
Add support for a different current working directory

### ISSUE THREAD

**Issue by DrKGD** [frabjous/knap#4]
I'd like to work with some tex documents in a subfolder of the current working directory (reason being I'd like to use telescope and other context aware plugins).

```
...
%docroot%     the name of the root document that needs to be processed*
%outputfile%  the name of the output file**
...
```
 
While with the _default settings_ `%docroot%` seems to retrieve the right filename (in fact invoking manual compilation with `process_once` seems to work just fine as the file updates, `toggle_autopreview` also compiles the file but fails opening automatically the pdfviewer), `%outputfile%` seems to point to the wrong path, in fact it is pointing to the current working directory with the expected output filename, thus ultimately failing to open the previewer.

E.g. sioyek reports "Could not open file: /absolute/path/cwd/main.pdf", while the document is located at /absolute/path/cwd/doc/main.pdf
```
├── doc
│   ├── main.aux
│   ├── main.log
│   ├── main.pdf
│   ├── main.synctex.gz
│   ├── main.tex
│   └── texput.log
```

main.tex is a simple tex document which has sets the TeX root to itself
```tex
% TeX root = main.tex
\documentclass{article}

\begin{document}
  Hello world!
\end{document}
```

In the plugin documentation it is reported that `** The output file is assumed to be the same as the root document with the output extension replacing the input extension of the routine.`. Am I doing something wrong or maybe this is not behaving as intended?

Either way, thanks a lot for both your attention and the plugin itself!

**Comment by frabjous** [comment]
It hadn't really occurred to me that people would put the root document in a different folder. It would be good to support this, and I do think I would have to make some changes, but I'm a little confused about your use case and the results you're seeing.

Is the file you're editing in a subfolder of the folder with the root document, or vice-versa? The example main.tex document you cited doesn't have any `\input` or `\include` commands, so how is the file you're editing related to it? What does the `TeX root = ` line of *that* file look like? (That's the one that matters, not what's at the top of main.tex, assuming main.tex is its root document.) And where is that file? Directly in cwd, or in a subfolder of root?

When I try to recreate your issue, I get a different result. If I put the document I'm editing in `cwd`, have it have `TeX root = doc/main.tex` at the top, have `\input{../inputted.tex}` insde it, and then run the plugin in it, the pdflatex command runs in cwd, and that's where main.pdf gets produced. Sioyek still can't find it, but for the opposite reason you cited: it looks for it as `cwd/doc/main.pdf` but it's actually at `cwd/main.pdf`.

I do want to fix this, and one thing is clear already: the process should be run from inside the folder with the root document, not from inside the folder with the current document, but I'd like to understand what's really going on with your use case first.

**Comment by frabjous** [comment]
Or maybe I'm misunderstanding entirely: is it just *neovim's* cwd that's different, and the only file you're editing is main.tex (in doc/main.tex relative to it)?

**Comment by DrKGD** [comment]
It was in fact a single file-only example, so the main.tex you see is the only document I am actually modifying, so the latter

> Or maybe I'm misunderstanding entirely: is it just _neovim's_ cwd that's different, and the only file you're editing is main.tex (in doc/main.tex relative to it)?

is exactly what I am doing.

**Comment by DrKGD** [comment]
At this point I think I should at least supply a MRE
Suppose the root directory of my project is PluginExample, so the following is the entire tree

```
PluginExample
└── doc
    ├── main.aux
    ├── main.log
    ├── main.pdf
    ├── main.synctex.gz
    └── main.tex
```

Suppose that I run nvim as currently being cwd in PluginExample folder so that by running `:pwd` (which stands for print working directory) I'd get 
```
/home/user/PluginExample/
```

Again, main.tex has the same content as before, so
```
% TeX root = main.tex
\documentclass{article}

\begin{document}
  Hello world!
\end{document}
```
 

Now _hopefully_ you should get an error on the pdfviewer whenever you are trying to run `toggle_autopreview` saying that `/home/user/PluginExample/main.pdf` does not exist, but on closer inspection pdf compilation of the document successfully happened.

**Comment by frabjous** [comment]
I see. I just assume LaTeXers have autochdir set, because LaTeX doesn't generally behave well if you try to process from a different folder. But I think I can make it spawn the processes from the right folder even if Neovim isn't working in that folder.

Once fixed, the self-referential root= shouldn't be necessary.

Stay tuned. I hope this won't be too hard to implement.

**Comment by frabjous** [comment]
I just pushed a commit that I hope may solve your problem. Please let me know either way, and thanks for the report.

**Comment by DrKGD** [comment]
> I just pushed a commit that I hope may solve your problem. Please let me know either way, and thanks for the report.
> 
> I should note that `%srcfile%` is now expanded to the _full_ path of the source file, but `%docroot%` and `%outputfile%` are the basenames of the document root and output file, and all processing and viewing commands are run from inside their directory.
> 
> There shouldn't ever be a need for a file to point to itself as its own root file, fingers crossed.

Everything seems to be working just fine, with and without the `% TeX root = main.tex`!
Guess you can go ahead and close this issue, thanks and keep up the good work!
